version: 1.0.{build}

image: Visual Studio 2017

services:
  - mssql2014

artifacts:
  - path: bin\SmogFightClub.zip
    name: SmogFightClub

before_build:
  - git submodule update --init --recursive

build_script:
  - ps: .\scripts\build.ps1

after_build:
  - 7z a %APPVEYOR_BUILD_FOLDER%\bin\SmogFightClub.zip %APPVEYOR_BUILD_FOLDER%\src\SFC\bin\Debug\netcoreapp2.2\*

test_script:
  - ps: .\scripts\test.ps1

