build:
  project: SmogFightClub.sln 

services:
  - mssql2014

before_build:
  - nuget restore

configuration: Debug

artifacts:
  - path: bin\SmogFightClub.zip
    name: SmogFightClub

test:
  assemblies:
    - src\SmogFightClub.Tests\bin\debug\netcoreapp2.2\SFC.Tests.dll

before_test:
  - ps: C:\projects\nsonar\scripts\appveyor-before-tests.ps1

after_build:
  - 7z a %APPVEYOR_BUILD_FOLDER%\bin\SmogFightClub.zip %APPVEYOR_BUILD_FOLDER%\src\SFC\bin\Debug\netcoreapp2.2\*